import colorama
import inspect
from colorama import Fore, Back, Style
import time
for i in dir(colorama):
    print(i)
print("------------------------")
print("Is colorama module")
print("------------------------")
print(inspect.ismodule(colorama))
print("------------------------")
print("Is colorama class")
print("------------------------")
print(inspect.isclass(colorama))
print("------------------------")
print("Is colorama function")
print("------------------------")
print(inspect.isfunction(colorama))
print("------------------------")
print("Type of colorama")
print(type(colorama))
cl = colorama
print("------------------------")
print(colorama.__name__)
print(cl.__name__)
print("------------------------")
print("Examples")
print()
print("Open it in CMD")
print()
print("You have 20 second to look the result than program will close if u are looking this in CMD")
print()
colorama.init()
print(f"{Fore.RED}Red Text")
print(f"{Fore.GREEN}Green Text")
print(f"{Fore.YELLOW}Yellow Text")
print(f"{Fore.BLUE}Blue Text")
print(f"{Fore.MAGENTA}Magenta Text")
print(f"{Fore.CYAN}Cyan Text")
print(f"{Fore.WHITE}White Text")
print()
print(f"{Back.RED}B{Back.GREEN}A{Back.YELLOW}C{Back.BLUE}K{Back.MAGENTA}G{Back.CYAN}R{Back.WHITE}O{Back.RED}U{Back.GREEN}N{Back.YELLOW}D{Back.BLUE}!")
print(f"{Back.RED}Red Background")
print(f"{Back.GREEN}Green Background")
print(f"{Back.YELLOW}Yellow Background")
print(f"{Back.BLUE}Blue Background")
print(f"{Back.MAGENTA}Magenta Background")
print(f"{Back.CYAN}Cyan Background")
print(f"{Back.WHITE}White Background")

time.sleep(20)
